name:  下载jable

on: [push, workflow_dispatch]

jobs:
  download_jable:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout
        uses: actions/checkout@v4

      - name: 2. python init
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.14'

      - name: Install FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v3
        with:
          ffmpeg-version: release

      - name: 3 赋予执行权限
        run: chmod +x ./N_m3u8DL-RE

      - name: 4. 运行
        run: python main.py
