name:  下载jable

on: [push, workflow_dispatch]

jobs:
  download_jable:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout
        uses: actions/checkout@v4

      - name: 2. python init
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.14'
          cache: 'pip'

      - name: Install FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v3
        with:
          ffmpeg-version: release

      - name: 3 赋予执行权限
        run: chmod +x ./N_m3u8DL-RE

      - name: 3. 安装 Python 依赖
        run: |
          pip install -r requirements.txt
      - name: 4. 运行
        run: | 
           python -m playwright install --with-deps chromium
           python telegram.py 

      - name: 5. 百度
        run: | 
           python baidu.py 

      - name: 6. 上传爬取结果
        uses: actions/upload-artifact@v4
        with:
          name: crawler-data        # 下载时的文件名
          path: finish.m3u8
          if-no-files-found: ignore
